### ISSUE TITLE
Break the project into modules

### ISSUE THREAD

**Issue by deniskrizanovic** [j-fischer/rflib#2]
Hi,

It would be cool if project was more clearly componentised. Maybe 4 different apps, or something. So that those of us, who like some of the features, but can't adopt others, can pick&choose.

Otherwise, great work.

**Comment by j-fischer** [comment]
Hi @deniskrizanovic ,

happy to look into this in the near future. I bundled the components together because of the benefits of combining features, i.e. logging and feature switch built-in into the trigger framework. My preference would have been to create a more loosely couple architecture, I haven't had the time to further investigate the complexities of package dependencies between Salesforce unlocked packages.  

What component are you primarily interested in, the logging framework? 

Thanks for the feedback!

**Comment by deniskrizanovic** [comment]
Yep, it was the logging framework I was interested in mostly. But, not
discounting the Feature Flagging too. We're already committed to a trigger
framework.

**Comment by j-fischer** [comment]
Hi @deniskrizanovic ,

did you (plan to) install the package or use the repository for your implementation of RFLIB? 

If you are interested, check out https://github.com/j-fischer/rflib/tree/feature/multi-modules and let me know what you think. So far, things are looking alright but I need to do a fair bit of testing before I can release it.

**Comment by deniskrizanovic** [comment]
Hi Johannes,

I like it. The dependency on the logger is also very light. Essentially it
boils down to "Logger.*", which any custom logging framework would also
implement, so in a sense, they are almost completely decoupled.

I will most likely use the repo. There will be some client-specific things
I may need to inject into places.
