### ISSUE TITLE
Package Dependency

### ISSUE THREAD

**Issue by kurtfairfield** [j-fischer/rflib#24]
**Describe the bug**
When going to install the most recent version of RFLIB-TF 1.1.0, with RFLIB-FS 2.3.0 installed (only package installed, no earlier usage) and has RFLIB code deployed from Andy in the Cloud tool. Get an error message.

` Invalid Upgrade. | The package you're installing depends on package 'RFLIB-FS', version '1.0'. Install package 'RFLIB-FS' in the target org before you install package 'RFLIB_TF'.`
-- | --

**Version**
Installing RFLIB-TF 1.1.0 with RFLIB-FS 2.3.0 already installed, no FS v1 installed ever.

**Code Snippets**
n/a

**Expected behavior**
package should have installed

**Screenshots**
see text msg above

**Desktop (please complete the following information):**
 - OS: W10Pro
 - Browser Chrome
 - Version current version

**Smartphone (please complete the following information):**
n/a

**Additional context**
all done in sandbox, trying a few other installation processes, maybe if I install FS v1 first then go to FS v2 after...

**Comment by kurtfairfield** [comment]
...workaround is to install packages in order. RFLIB-TF 1.1.0 needs to see RFLIB-FS 1.0.

This flow worked... maybe could skip FS 1.0.2 and do FS 1.1.0 right away, not sure...

RFLIB 2.2.0
RFLIB-FS 1.0.2
RFLIB-TF 1.1.0
RFLIB-FS 2.3.0
RFLIB-FS 1.1.0

All good, installed and working properly. Feel free to close Johannes...

**Comment by j-fischer** [comment]
Hi @kurtfairfield , 

thanks for opening this and sorry for the delayed response, I've been heads down at work and mostly ignored my personal emails. Just so that I understand, were you able to execute the following installation flow successfully? 

RFLIB 2.3.0
RFLIB-FS 1.1.0
RFLIB-TF 1.1.0

I have to admit that I am still struggling a bit to get a clean handle on managing the package dependencies. In my earlier days of the project, I always upgraded the dependencies, but I moved away from it to make the packages easier to consume. 

Right now, the `sfdx-project.json` file contains the minimum versions for the dependencies. But I expected that you should always be able to install the latest versions without Salesforce throwing a fit. If that is not the case, I may have to rethink the strategy and upgrade the dependencies more often again. 

Looking forward to hearing back from you! 

Thanks

**Comment by j-fischer** [comment]
I tested dependencies and it should be fine to always install the as long as the min-version dependencies are fulfilled. Closing this ticket for now.
