### ISSUE TITLE
rflib_DatabaseDmlExecutor code coverage

### ISSUE THREAD

**Issue by mikbranchaud** [j-fischer/rflib#52]
We use the --testlevel RunSpecifiedTests parameter in our CI/CD pipeline deployment setting with --runTests set to a list of each test class.  This allows us to explicitly exclude certain long running tests so that our deployment job to our development/test stack can be optimized.  Unfortuneately, using this parameter means that each individual class referenced must individually have 75% code coverage rather than a 75% average for the whole organization.  We have accomplished this but while attempting to upgrade to the latest version of the logging framework, the introduction of the rflib_DatabaseDmlExecutor prevents us from maintaining this metric since it has 0% coverage.

Looking into the rflib_LogArchiveControllerTest class, testClearArchive_Success, I see that rflib_LogArchiveController.DML_EXECUTOR is mocked but I am not clear on the reasoning.

**Comment by mikbranchaud** [comment]
Note, I created a new test class, rflib_DatabaseDmlExecutorTest, to get 100% coverage of rflib_DatabaseDmlExecutor .

@isTest private with sharing class rflib_DatabaseDmlExecutorTest {
    private static rflibDmlExecutor DML_EXECUTOR = new rflib_DatabaseDmlExecutor();
    @isTest private static void testDatabaseDmlExecutor() {
        //use rflib_DatabaseDmlExecutor  to get coverage
        List<Group> someGroupList = new List<Group>{new group(
            DeveloperName = 'Some Group',
            Name = 'Some Group'
        )};
        DML_EXECUTOR.insertImmediate(someGroupList);
        DML_EXECUTOR.deleteImmediate(someGroupList);
    }
}

**Comment by j-fischer** [comment]
Hi @mikbranchaud , 

As always, thanks for opening the ticket. As for your question on why the executor was mocked: that's because unit testing Big Objects DMLs is (was at the time) not supported by Salesforce. The platform threw an exception in the unit tests and that is the reason why I introduced the mock. 

Not creating a test for the mock was simply an oversight on my part as I was focused to get the Big Object part out. 

I am working on some other unit test improvements this weekend and will include your test class as part of it. 

I will post the new package version once release. 

Cheers

**Comment by j-fischer** [comment]
Hi @mikbranchaud ,

RFLIB 3.1.2 has been released with your changes included. Please let me know if you have any issues. 

Cheers,
Johannes

**Comment by j-fischer** [comment]
@mikbranchaud Oh, and I totally forgot to mention: 

Thanks for providing the code snippet, I very much appreciate the support!
