### ISSUE TITLE
Issue with with reading reportingLogLevel from custom setting

### ISSUE THREAD

**Issue by akmware** [j-fischer/rflib#6]
https://github.com/j-fischer/rflib/blob/6c414ec04a92b39e9e9177549919de8e8c2dc43c/rflib/main/default/classes/rflib_DefaultLogger.cls#L197

I've been playing around with this fantastic library for a client and I simply couldn't figure out why we need to encompass log levels for the reportingLogLevel and for the others we rely on the custom setting in the DefaultLogger class

I've updated my fork to read

`reportingLogLevel = newLevel;`

It's now working for me as I like it to. But I'm curious to understand why it's like that, to begin with.

**Comment by j-fischer** [comment]
This is totally a bug. Will be fixed in the next version. Thanks for using RFLIB and reporting this issue, @akmware

**Comment by j-fischer** [comment]
Actually, @akmware , there is a reason for this behaviour, I had to remind myself: 

What you are seeing here is a protection of the framework from itself. Basically, the rule is that the `reportingLogLevel` can only be set to INFO, WARN, ERROR, FATAL, or NONE. 

The reason why this condition was introduced lies in the trigger framework (TF package) and the history of RFLIB. Version 1.0 was a single package with a trigger handler that would send out the email notifications. Now, the trigger framework itself contains DEBUG log statements so that users can see what happened inside the framework when one or more triggers are executed, specifically to provide transparency in a recursive trigger situation. 
If the `Reporting Log Level` is set to DEBUG, those statements would cause an infinite loop of log events to be created and bring an org down to its knees from a performance perspective. I introduced this guard after I ran into this issue myself in a Sandbox. 

To make sure that the logging and trigger framework play nice together, I added this condition to protect users from making the mistake of creating this infinite loop in production.

I hope that answers your question. I will mark this issue as a won't fix. Sorry for the initial confusion.
