### ISSUE TITLE
Install Fails for RFLIB-FS 2.0.0 - due to Apex Compile Failure - workaround proposed

### ISSUE THREAD

**Issue by kurtfairfield** [j-fischer/rflib#61]
**Describe the bug**
Cannot install RFLIB-FS ver 2.0.0

**Version**
Installed RFLIB 4.0.0 successfully, trying to install RFLIB-FS 2.0.0

**Expected behavior**
should install

**Screenshots**
If applicable, add screenshots to help explain your problem, i.e. Chrome Dev Console.

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Chrome
 - Version 103.0.5060.66

**Additional context**

```
Your request to install package "RFLIB-FS ver 2.0.0" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.

If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.

Organization: redacted (00D0r0000008dbo)
User: redacted (0051K000008fbLK)
Package: RFLIB-FS (04t3h000004sq5x)

Problem:

1.  Apex compile failure
Apex class rflib_TriggerManagerTest: line 42, column 47: Variable does not exist: rflib_UserFactory

2.  Apex compile failure
Apex class rflib_TriggerManagerTest: line 43, column 54: Variable does not exist: rflib_UserFactory

```
**Workaround**

Selecting the option to not compile all Apex classes works to allow the installation. Wanted to make sure this was a viable workaround, or perhaps is even best practice. But as I do not fully understand the root cause of why this is a blocking issue for install,  thought I would ask the questions.

<img width="706" alt="image" src="https://user-images.githubusercontent.com/18200424/176953272-8ad22365-ab1e-4817-9d5a-9db3a7303d47.png">

**Comment by j-fischer** [comment]
Hi @kurtfairfield ,

Thanks for bringing this up. I moved the User Factory from RFLIB-FS to the RFLIB package and learned that it did not like this transition during the installation QA, which led me to rename the class to `rflib_TestUserFactory` and replaced its usage in the FS and TF package. 

I always run an installation and upgrade script before I release the packages, I am curious why this error did not come up and will re-run the tests again. But looking at the error, there is definitely an issue with the upgrade process because TF uses the User Factory class of the FS package and when you upgrade FS with the full compilation, it must have removed the original file `rflib_UserFactory`, which caused the TF package to fail compilation. 

Therefore, I believe your workaround is valid assuming that you would upgrade the TF package right after. 

I will take a look later this week if I can find some way to improve the installation experience in a future release. 

But assuming that you upgrade TF right after the FS package, you should be fine and I would expect that all unit tests are passing. Could you please have a look and confirm that this is the case?

Thanks,
Johannes

**Comment by kurtfairfield** [comment]
@j-fischer - thanks for your reply. Yes the workaround seems to be the right choice. I ran all tests in the org and everything passes (except for rflib_SendLogEventEmailActionTest for obvious reasons).
