### ISSUE TITLE
Does logger need to be declared as static?

### ISSUE THREAD

**Issue by kurtfairfield** [j-fischer/rflib#63]
**Is your feature request related to a problem? Please describe.**

Looking for some clarification here. In all you example code, you instantiate a logger class as static, always from what I could see. So I copy the pattern and declare all logger static.

But when I instantiate a static logger instance on an Apex defined type that is used in a Screen Flow, the flow engine breaks hard. Change it to non-static, and no issues. The Apex defined type really does not need any logging, I just am following your best practices and putting a logger instance in all classes. This Apex defined type is used a Data Transfer Object (DTO) to hand complex data structure between the flow and invocable actions.

**Describe the solution you'd like**

Just want to know if a non-static logger instance is a viable usage, and if not can you give me a brief explanation why? I had a look at the code base, but could not find any reason it should/must be static, except maybe to be more efficient?

**Can this be done by combining existing functionality of RFLIB or Salesforce**

Yes, I think it works just fine as non-static declaration

**Additional context**

Here is the class usage... removing 'static' from line 14 solves all my Screen Flow errors.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/18200424/183534212-2324720b-d3fb-49c6-b5c5-0282b356d916.png">

Here is the ugly Screen Flow error - no logs are created about this error in FLOW or in the debug logs...

<img width="488" alt="image" src="https://user-images.githubusercontent.com/18200424/183534708-32e91df8-3154-4846-936a-ba147547cb4c.png">

<img width="486" alt="image" src="https://user-images.githubusercontent.com/18200424/183534747-c34c1738-9c1d-4674-9b29-4f8e1b875660.png">

**Comment by j-fischer** [comment]
@kurtfairfield Interesting issue. I can certainly attest that had not tested this scenario previously, so thanks for pointing this out. 
Looking at the error message, there is nothing that stands out to me at this point as to why this error would happen. I'll have to see if I can come across it myself in the future. But just as an FYI, I don't see it as priority for the moment. 

The good news is, you have already found a viable workaround! 
To answer your question:

**Every logger can be instantiated as a non static instance. There is absolutely no problem with that and logging should work like you expect it since all necessary state inside the logger instance is static, so there is no conflict.** 

Declaring the logger as static is really just a design choice based on the fact that most of the state is inside of it is static. In addition, there are situations when I use a static constructor in classes and in order to log in those, the logger has to be static as well. The **convention** behind this is that there should only be one logger instance for each context, even if you create multiple instances of a class with a logger, but there is no functional need for this. You can create 3 logger instances in a row with the same context, use them interchangeably and logging works just like you are used. 

I hope this answered your question. Please let me know if there are any follow-up questions. 

Cheers :)

**Comment by kurtfairfield** [comment]
@j-fischer - thanks for the detailed explanation. I wasn't 100% sure if the code would complain about having multiple loggers for the same object. I have a request into SF Support to get the answer from behind the curtain (if there is one) about what is the root cause in the flow engine of that somewhat non-descript error. Thanks for the speedy reply:)
