### ISSUE TITLE
Question on Email addresses used...

### ISSUE THREAD

**Issue by kurtfairfield** [j-fischer/rflib#64]
Wondering about the Custom Settings for Email...

```
Email Log Level : Defines what Log Events should be sent out to the Apex Exception Email list.

Org Wide Email Sender Address : Defines the email address to be used to send out the email notifications.
```

The first setting sets the threshold for when RFLIB log is emailed 'to the Apex Exception Email list'. Why then do we need another Email Address specified? Are their multiple email notification processes at work here, that required a different email address?

It looks to me that a copy of the logged message will then go to the entire Apex Exception Email list and the Org Wide Email specified as well?

I am running some tests, but thought I would ask the question as well.

Your thoughts?

**Comment by j-fischer** [comment]
Hi @kurtfairfield , 

The org wide sender address is used to sent out the message (from header), it should not be a recipient unless it is stored under the email exception list through an assigned user or listed email address. 

The reason why the setting exist is that I have worked in environments where there were multiple verified email address in the org for different purposes so RFLIB could not just pick one but needed to use a specific one. 
So, the email address listed in this setting must match a verified email addressed that is configured in the Organization Wide Email Addresses under Setup, or the email would otherwise not be sent. 

Let me know if this answered your question or if I missed anything. Once we complete this thread, I will look into improving the documentation around this setting. 

Cheers,
Johannes

**Comment by j-fischer** [comment]
Closing this question, please re-open if there is anything outstanding. Thx
