### ISSUE TITLE
Flush LOG_STATEMENTS after reporting?

### ISSUE THREAD

**Issue by Confirm4Crit** [j-fischer/rflib#7]
I'm wondering why we don't flush the LOG_STATEMENTS list after reporting it?
There might be a time where I want to fire 2 warns, and they end up building a stack across the events?
```
rflib_Logger LOGGER =rflib_DefaultLogger.create('My Super Cool Context');
LOGGER.warn('warn  ' + '\n' + ' I am a message body that had new lines in it');
LOGGER.warn('warn2');
```
Something like above will give me two platform events
![image](https://user-images.githubusercontent.com/3483618/90651501-126ef280-e20b-11ea-8616-15a68e639394.png)

**Describe the solution you'd like**
Let's flush the log out after we've had a successful event?
https://github.com/j-fischer/rflib/blob/df676c90c79e5b1cf7132f967319ba8b24871417/rflib/main/default/classes/rflib_DefaultLogger.cls#L362
```
public class PlatformEventPublisher implements EventPublisher {
    public void publish(rflib_Log_Event__e event) {
      Database.SaveResult result = EventBus.publish(event);     
      if(!result.isSuccess()) {
        System.debug(LoggingLevel.ERROR, JSON.serialize(result.getErrors()));
      }
// FLUSH here, maybe?
    }
  }
```
**Can this be done by combining existing functionality of RFLIB or Salesforce**
Am I missing a design reason for this? Would I just make my own logger implementing `rflib_Logger` myself, and not influence the default logger?
Was it expected to just use `createBatchedLogger` if I wanted this functionality?

Main reason for calling this out here is I don't want instantly split my own fork far away from base rflib.

**Comment by j-fischer** [comment]
Hi @Confirm4Crit ,

in earlier, unpublished versions of the framework, I actually used to flush the list of log statements after publishing. However, as I was using the framework more, I moved away from it. The reason for this is that when dealing with possible complexity for stitching together log statements from various Log Events to get a full picture of what was going on. Especially when you are reducing the log level to INFO, you could get a lot of Log Events for a single transaction. By not flushing the LOG_STATEMENTS list, the last event you will receive for a transaction/user will contain all the log statement. I know that there are a number of events sent before that will be redundant in that case, but the efficiency and convenience of the single log file trumps the "waste" of resources, in my opinion. Especially in production environments where one could deal with events coming in from multiple resources, this approach is more useful as you don't have to deal with the noise. (obviously, in a DEV sandbox, the situation looks quite differently). 

This all was done before the Batch logger was created. The Batched Logger's purpose is to deal with the "DML before web service" error. When I started out to build it, every log event to be published was stored in a list and then I published all events in one go. However, due to the fact that the framework does not flush the `LOG_STATEMENTS` list, the Batched Logger was able to simply store the last event to be published because it would contain all the log statements from the previously published event. This is a lot more efficient because it will only create a single Platform Event for the transaction, which reduces the governor limit consumption. Depending on the number of publishers and listeners you have, this can have a quite a big impact, especially for orgs that use Platform Events heavily for their own business logic and RFLIB would compete for those daily limits. 

So, to answer your questions: It is best practices to use the Batched Logger as it does make the code more future proof, i.e. for when you introduce a outbound web request later on. It also will make the framework more efficient. But it comes at a cost of using the try-finally pattern and that you have to call the `publishBatchedLogEvents()` method in every transaction. 

As a reference, you can always (even just temporarily) clone the `rflib_DefaultLogger` class, implement your changes and use the Logger Settings custom object to decide which implementation to inject into your classes. There would not be the need to fork the entire project, and you could switch back later when your missing feature is implemented, or if you like to adopt new features via a package upgrade. 

Last, I am totally open for adding control to flush the `LOG_STATEMENTS` but I am not sure yet on what the best approach for this is. I would like to leave the current behaviour as a default, so that I don't break backwards compatibility. On first thought, this could be done through an overload of all the functions with a 3rd parameter that would indicate whether to flush, i.e. `LOGGER.warn('my message', null, true);`, or via a configuration setting, i.e. a "Flush Logs Level" with the standard log levels as values. If the log event gets published and the Flush Logs Level is equal or lower to the level of the event to be published, then it would the flush the list. 

These are just two thoughts? I am very open for feedback on the approach at this point. 

Thoughts, anyone?

**Comment by Confirm4Crit** [comment]
`By not flushing the LOG_STATEMENTS list, the last event you will receive for a transaction/user will contain all the log statement.`

This is maybe where I'm getting a little lost, if I were to use an apex trigger and parse out the log messages, how would I know it's the *last* one? Attach UUIDs to each message, upsert on that? (Haven't had coffee yet if I'm just not seeing it).

**Comment by j-fischer** [comment]
Oh, I see, you are trying to parse the log statements programmatically. 

I think I don't fully understand what you are trying to accomplish, are you storing the logs somewhere else? Identifying the "last message" is generally a tricky task because this depends on the configuration of the custom settings, which can change, and there could always something happen between two log statements that cancels the transaction. 

Now, the one thing I can say is that the last line in the `Log_Messages__c` field should always contain the last log message, which also caused the `Log_Level__c` to be set. Since the log messages are structured in a way that is regex friendly, maybe this would work for you. 

If you could explain to me what you are trying to accomplish a bit more, I'd be happy to see if there is a current way of doing this already.

But as I said, you are presenting a use case that certainly benefits from having control over the flushing behaviour. Have you had a chance to take a look at the two solution approaches? Do you have any preferences?  

Cheers

**Comment by Confirm4Crit** [comment]
When I said last, I meant event, sorry.
Even with the batch job, if I had a reason to fire it *twice*, I'd end up with this:
```
rflib_Logger LOGGER =rflib_DefaultLogger.createBatchedLogger('Account API');
LOGGER.warn('warn1 \n lol new line example');
LOGGER.warn('warn2');
LOGGER.publishBatchedLogEvents();
LOGGER.warn('warn3');
LOGGER.publishBatchedLogEvents();
```
![image](https://user-images.githubusercontent.com/3483618/91105104-2f595a80-e63d-11ea-8eb6-4ea0c1f67b71.png)

I've got an apex trigger that's listening to the events, parsing them out, and throwin' em to an sobject.
I don't know that I've already saved warn1 and 2 already on the second firing.

I'm going to assume a single batched logger isn't expected to fire `publishBatchedLogEvents` twice? If I wanted a real time push, use the regular logger, and burn the dml statements?

`I know that there are a number of events sent before that will be redundant in that case, but the efficiency and convenience of the single log file trumps the "waste" of resources, in my opinion.`

I guess that's where I'm getting a little crossed up, how do I know I've actually gotten the last event for a specific logger?
That's *why* I'm thinking I want to flush.

There's going to be situations where I want to save entities but keep pushing:
Log a req from an api, do stuff with that req.
```
rflib_Logger LOGGER =rflib_DefaultLogger.create('Account API');
LOGGER.warn('I am a request body');
LOGGER.warn('You did stuff with that body, cool');
```
![image](https://user-images.githubusercontent.com/3483618/91105780-fc17cb00-e63e-11ea-8458-51850e21929f.png)
You end up in the same situation, how does my consumer *know* the first log is truly redundant? 
---
An insanely sloppy way to demo what I'm getting near is this:
```
public class PlatformEventPublisher implements EventPublisher {
        public void publish(rflib_Log_Event__e event) {
            Database.SaveResult result = EventBus.publish(event);
            if (!result.isSuccess()) {
                System.debug(LoggingLevel.ERROR, JSON.serialize(result.getErrors()));
            }
            LOG_STATEMENTS.clear();
        }
    }
```
```
private class BatchPlatformEventExecutor implements Queueable {

        ...
            if (!result.isSuccess()) {
                System.debug(LoggingLevel.ERROR, JSON.serialize(result.getErrors()));
            }
            LOG_STATEMENTS.clear();
        }
    }
```

Apologies if this rant is a little violent, on little sleep right now, but wanted to send this out before EOD.

**Comment by j-fischer** [comment]
Ok, I think I understand a bit more now what you are after.

If you truly want only a single event per transaction, the Batched Logger is exactly what you need. However, the key difference implementation detail to note is that there should only be a single call of `LOGGER.publishBatchedLogEvents()` per transaction, ideally at the last line of execution. The sample on the README page hopefully gives you the right idea:

```
@AuraEnabled
public static String doSomething(){
    try {
        LOGGER.warn('warn1 \n lol new line example');
        LOGGER.warn('warn2');
        // more code
        LOGGER.warn('warn3');
        // Application logic here
        return 'Result';
    } catch (Exception ex) {
        LOGGER.fatal('DoSomething threw an exception', ex);
    } finally {
        // Will only publish a single Log Event containing all three WARN messages when the transaction is about to complete. 
        // This will be the last event that fulfilled the conditions to be published and will include all 
        // log messages up until that specific point.
        LOGGER.publishBatchedLogEvents();
    }
}
```

In this case, the call is made at the end of a Aura Controller methods, but the context could also be a trigger, invocable action, etc. 

Assuming that your code is organized in controllers and service classes, the `publishBatchedLogEvents()` method would only be invoked by the controller. Service classes would expect this managed by the consumers and would never call  `publishBatchedLogEvents()`  themselves. 
As you can see, there is a lot more effort involved with the batched logging, but some good benefits come out of it. Only the last log event to be published will be held onto by the `BatchPlatformEventExecutor`. When the publishing method is invoked, that is the event to be sent out. Batched logging relies on the fact that `LOG_STATEMENTS` are not cleared and was designed with the intention that  `publishBatchedLogEvents()` is only invoked once. 

Anyhow, the more I think about it, the more I feel that flushing the LOG_STATEMENTS triggered by a Log Level based configuration value would be a viable option to do what you need without impacting existing implementations. 

I will add it as an enhancement for one of the next couple versions.  

In the meanwhile, did my explanation on how to use batched logging make sense? If not, I am more than happy to continue to the conversation.

**Comment by Confirm4Crit** [comment]
I'm with you on batched, I guess I'm attempting to use this library to just *save benchmarks steps* of a process.
My custom apex endpoint gets a body, let's log it.
Let's also log what they've did.
Uhoh, exception, log it.

I can do a batched logger, it'll work fine, save it on exception or finish, etc.

But if I didn't want to use a batched logger, and fire the event *instantly*, *multiple time* though a transaction, I kinda feel like I'm stuck?

I'm just still not sure how I safely know that a logger is *done* from a consumer POV, without, like, tagging the last message with some sort of indicator?

**Comment by j-fischer** [comment]
What you described is one way that I can think off from a tag-the-last-message perspective. Another option I can think of is to instantiate two loggers with different Context strings, i.e. "MyContext" and "MyContext-end": 

- `LOGGER_A` would be the one to write all standard log statements. 
- `LOGGER_B` would be used for the very last one. 

Then you can simply check the context string ("MyContext-end") in your trigger to further process the log data. 

Would that help?

**Comment by j-fischer** [comment]
@Confirm4Crit I browsed the release notes for Winter 21 this weekend. Salesforce is introducing a new governor limit for Platform Events in Apex. This means that the need to use the Batched Logger has been significantly removed. It's still a good use when it is important to be most resourceful around PEs, i.e. your organization uses PEs for business logic and is close to the limits, but using the standard logger will become my recommendation moving forward. Just wanted to let you know since this was part of our discussion. 

https://releasenotes.docs.salesforce.com/en-us/winter21/release-notes/rn_platform_events_publish_immediate_limit.htm

**Comment by j-fischer** [comment]
@Confirm4Crit Just to let you know that version 2,1 is released with the new option to flush the `LOG_STATEMENTS`.

Please let me know if you encountered any issues.

Cheers
