### ISSUE TITLE
Platforms events not firing

### ISSUE THREAD

**Issue by lfloreznexthink** [j-fischer/rflib#71]
After installing it in a developer edition, because it is also not working on a Sandbox, I get no logs. I used the gitHub deploy button on a dev ed. Created the org level custom settings, added the permission set to my own user. I get no logs in the Log Monitor. Then I decide to do some debugging and it seems that the Platforms events are not firing. The permissions on "Log Events" are "Read" and "Create" on the profile. I activated debug logs for "Automated Process" entity and created a new event (snippet below) and I received nothing. I am clueless what I could be possible missing. I really appreciate your help here.

**Version**
Master branch

**Code Snippets**
rflib_Log_Event__e ev = new rflib_Log_Event__e(
	Context__c ='',
    Log_Level__c = 'DEBUG',
    Log_Messages__c = 'test',
    Platform_Info__c = 'info',
    Request_ID__c = 'id'
);
EventBus.publish(ev);

**Expected behavior**
Logs in the Automated process. Log records in the log monitor.

**Custom settings**
Archive Log Level	INFO
Batched Log Event Reporting Level	NONE
Client Console Log Level	INFO
Client Log Size	100
Client Server Log Level	WARN
Email Log Level	NONE
Enable Log Masking	
Flush Log Cache Level	NONE
Functions Compute Log Level	DEBUG
Functions Log Size	100
Functions Server Log Level	INFO
General Log Level	INFO
Log Event Reporting Level	INFO
Log Finalizer Class	rflib_DefaultLogFinalizer
Log Size	100
Log Timer Class	rflib_DefaultLogTimer
Logger Factory Class	rflib_DefaultLoggerFactory
Org Wide Email Sender Address	
System Debug Log Level	DEBUG

**Comment by j-fischer** [comment]
Hi @lfloreznexthink , 

First of all, sorry for the late reply. I don't have a ton of time these days to check on personal emails and the github notifications get therefore easily missed. 

I'd be happy to help you through this but we have to start with some changes to your strategy about evaluating the tool if that's ok. 

For starters, please make sure to assign the correct permission sets to your user accounts. There is a permission set for creating log events and one for using the management console. Now, theoretically, as an admin you should not need those but let's do this more as a sanity check, please. 

Next, I would like you to use the Apex `rflib_Logger` class to write your log statements. There is a lot that happens behind the scenes that the logger does before submitting an `Log Event`. That's how the library is meant to be used. Also, it is the logger that handles most of the Custom Settings values that you posted. 

See the wiki for more details: https://github.com/j-fischer/rflib/wiki/Getting-Started-with-Logging#logging-in-apex

Another item in your test that I would like to point out is that your are submitting a "DEBUG" event. While it should show up in the console this way, DEBUG events are not meant to be actually published. I recommend to use ERROR or FATAL for your test to ensure that the log level settings are not filtering out messages.

RFLIB is optimized to reduce the Governor Limit consumption in your org, hence there are a lot of settings that filter messages from being published but added to the log stack instead. 

Try these things out and let me know how it goes. I will be monitoring this ticket more closely and check for your updates over the next two weeks. I am sure we can get you up and running soon. 

Cheers,
Johannes

**Comment by lfloreznexthink** [comment]
Hello,

Many thanks for getting back to me. I was able to find what the issue was.
I was under the impression that each call to the logger will be showed in the Log Monitor, hence, a Platform Event published. Maybe because I thought by reading the documentation that Batch logging was to do the publish event at the end by calling LOGGER.publishBatchedLogEvents(). Now I can see the logs in the Log Monitor after I call 

`logger.reportLogs();`

So I did:

`rflib_Logger logger = rflib_LoggerUtil.getFactory().createLogger('Test Context');
logger.trace('test-trace');
logger.debug('test-debug');
logger.error('test-error');
logger.reportLogs(); /*Please include this to the wiki page*/`

And now works great.
The manual Platform event I added in the previous comment was missing a required field "Context__c", that why it wasn't firing.

Now that I know how this works, I have a lot of work to do. Super happy how this works. Many thanks for this awesome tool.

**Comment by j-fischer** [comment]
@lfloreznexthink Awesome! Glad you figured it out and thank you for using RFLIB. :)

I do have a few more comments to help you get the most out of the library.

### Batch Logging

Batch logging was created in the very early days of RFLIB to avoid issues with HTTP Requests where the logging of an event would cancel any outgoing requests due to a pending DML operation. This concept was deprecated with the introduction of `EventBuss.publishImmediate()`. There are only very few edge use cases left for where the use of batch logging makes sense. Therefore, I would **generally not recommend** to configure the library for it. 

### Logger Settings

The publishing of log events is driving by log level settings in the custom settings object, but there are some dependencies that one needs to be aware of. 
For example, the **General Log Level** and the **Log Event Reporting Level** need to be aligned where the first setting defines what message are captured in the log stack and the second setting decides when a platform event is published. 
Check out the [Logger Settings Wiki Page](https://github.com/j-fischer/rflib/wiki/Logger-Settings) for details on all settings and the recommend values for development and production. 
In your example above, you may not ese the `TRACE` statement with the default configuration settings. The `ERROR` log statement should typically create a log event even without `logger.reportLogs()` present. 

### Best Practices

Keep in mind that RFLIB is optimized to reduce the Governor Limit consumption, so that the framework plays nicely in any production environment. Not publishing every log statement as a Platform Event is by design and I highly recommend to follow best practices around the log levels in your code to make your life in production a lot easier later on. I talk about the best practices in my [Apex Hour Talk](https://www.youtube.com/watch?v=zHEBDRstsZU). 

Last, just to confirm, creating Log Events directly is generally legit but not recommended as it bypasses all the logic that is implemented in the logger. 

Pleases don't hesitate to open more ticket with questions in the future. Happy to help! 

Cheers
